language: objective-c
osx_image: xcode7.1

# Set up our rubygems (slather and xcpretty, namely)
install: gem install slather xcpretty -N

before_script:
  - set -o pipefail
  
script: 
 - ./build.py

notifications:
  slack:
    secure: BIziStN+8QJLjdqNbLyRWWw9kI/MQsX+rZq+xz/bfTANk0gbEryLgMSiEoHxdoctu0dOqOet1voYuDKs3RQW3W0yh0AhDwVgWThNkTA0oDXF8zqm9AXettXNtmYHipaYb6+z6L4lpJOkClQp3hAheu8cM2igqye1O0FQla9g/PA=
