language: objective-c
osx_image: xcode7.1

before_install: gem install slather xcpretty -N
script: 
# Start by nuking any lingering codecov files. These can cause issues when the xcode version changes
  - find . -name "*.gcda" -print0 | xargs -0 rm
  
# Build and Test the ADALiOS library
  - xcodebuild test -workspace ADALiOS.xcworkspace -scheme ADALiOS -configuration CodeCoverage -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' | xcpretty -c

# Build the Test App (to make sure it doesn't break
  - xcodebuild -workspace ADALiOS.xcworkspace -scheme MyTestiOSApp -configuration CodeCoverage -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' | xcpretty -c

after_success:
# Slather sends codecov results to coveralls
  - slather
